services:
  - type: web
    name: quiz-platform-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://peddapalliabhinav_db_user:ytOxl35sXDoGTgi1@cluster0.cksk0co.mongodb.net/quiz-platform?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: supersecretkey
